/**
 * Low-quality image placeholders for hero slides.
 *
 * Generated by gen-lqip.mjs. These are inlined into the HTML, so the hero area
 * paints approximate colour immediately instead of showing a flat grey box
 * while the real image loads. That is what Speed Index measures, so it moves
 * the metric far more than shaving bytes off the real image does.
 *
 * Regenerate after changing any hero image.
 */
export const HERO_BLUR: Record<string, string> = {
  "/new-img/1.webp": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQAgCdASoQAAkAAwBSJbACdAD0kI/iMNqAAP712kLnj3+0CDeMfqq6N6+PfxRrrV9qK/i38rfzXLbPu8Hy7bFA4pllAFu9WY30NCzMs6cKqw+ZiwFnbvD69pH9FA/0kwn3+34+slS6XYX+Ue8Xb5k79Bna8AAA",
  "/new-img/2.webp": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQAgCdASoQAAkAAwBSJbACdDiMwPCU1/eAAP71e3MrM6p/1zQarBH3waAAO350VnQEnFTxlyu9f0UO7eUELGofNB7WxUv6F/+1/Srn8YmkIv+YQUucd8CuvRZ8nu7e7Pdgzy7mgAA=",
  "/new-img/3.webp": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwAQCdASoQAAkAAwBSJZACdAC4ZzjV8AAA/utYi0PdTRoF8dEVJ4UY0ICxyNQUHPNJGVbia++gHdNvqsgCWoDeCH8TORSGOZkLa9UDpJXUw/uXvoNAGD7XzyA7kVk7iyhC/tbwM9YkgQAA",
  "/new-img/4.webp": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwAQCdASoQAAkAAwBSJbACdAD0Q9jl5QAA/sxozV/d22F/h1mmLhbEFWt/RGuDjRYfIyP7ac75zHlUIoBvSzO/7KajozzQBXjQIDS55JeFo4JGwr923EM+DQYGQG1IGieYVwcTtA0JaAAA",
  "/new-img/5.webp": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAkAAwBSJQAB8llimftgSXjAAP7yv7kVT1gJRDvvJaKWqjXu/GPCCHuL0PUmwDmpbL0zydYZf6GMqABrYySQv3+hRG0uRSWYwNUQ4AA=",
  "/new-img/6.webp": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoQAAkAAwBSJQBOgCKV/S64d1MAAP7uy44gebLO+LROieZCacWYiB0U5xjhZYGhj5zRIahB5ma2rkQNgojteAAA",
};
